POST http://localhost:9000/api/budgets/setup/
Content-Type: application/json

{
    "year":2024
}

###
GET http://localhost:9000/api/budgets/
Content-Type: application/json

###
GET http://localhost:9000/api/expend_programs/available/2024
Content-Type: application/json

###

PUT http://localhost:9000/api/expend_programs/import/1
Content-Type: application/json

{
      "program_id": 1,
      "program_kode": "1.2.1",
      "program_name": "Program Pembinaan Dan Pelatihan Atlet Daerah",
      "unit_id": 3,
      "unit_kode": "1.2",
      "unit_name": "Bidang Pembinaan Prestasi"
}

###
GET http://localhost:9000/api/expend_kegiatans/available
Content-Type: application/json

{
    "expend_program_id":1,
    "year":2024
}
###
PUT http://localhost:9000/api/expend_kegiatans/import/1
Content-Type: application/json

{
      "kegiatan_id": 1,
      "kegiatan_kode": "1.2.1.1",
      "kegiatan_name": "Penyelenggaraan Pemusatan Pelatihan Daerah",
      "expend_program_id": 1,
      "budget_year": 2024
}

###
POST http://localhost:9000/api/expend_objects/rincian
Content-Type: application/json

{
     "objek_name":"Stabilo",
     "volume":5,
     "volume_name":"pcs",
     "satuan":1,
     "satuan_name":"paket",
     "expend_kegiatan_id":1,
     "price":10000,
     "account_id":21,
     "acc_kode":"5.2.02.01.011",
     "acc_name":"Belanja Alat Tulis Kantor"

}
###
PUT http://localhost:9000/api/expend_objects/ubah/16
Content-Type: application/json

{
     "objek_name":"Kertas HVS A4",
     "volume":20,
     "volume_name":"rim",
     "satuan":1,
     "satuan_name":"paket",
     "expend_kegiatan_id":1,
     "price":80000,
     "account_id":21,
     "acc_kode":"5.2.02.01.011",
     "acc_name":"Belanja Alat Tulis Kantor"

}
###
POST http://localhost:9000/api/expend_objects/rincian
Content-Type: application/json

{
     "objek_name":"Kertas HVS F4",
     "volume":5,
     "volume_name":"rim",
     "satuan":1,
     "satuan_name":"paket",
     "expend_kegiatan_id":1,
     "price":90000,
     "account_id":21,
     "acc_kode":"5.2.02.01.011",
     "acc_name":"Belanja Alat Tulis Kantor"

}
###
POST http://localhost:9000/api/expend_objects/rincian
Content-Type: application/json

{
     "objek_name":"Pulpen Hitam 0.4mm",
     "volume":10,
     "volume_name":"pcs",
     "satuan":1,
     "satuan_name":"paket",
     "expend_kegiatan_id":1,
     "price":8000,
     "account_id":21,
     "acc_kode":"5.2.02.01.011",
     "acc_name":"Belanja Alat Tulis Kantor"

}
###
POST http://localhost:9000/api/expend_objects/rincian
Content-Type: application/json

{
     "objek_name":"Pulpen Hitam 1.0mm",
     "volume":10,
     "volume_name":"pcs",
     "satuan":1,
     "satuan_name":"paket",
     "expend_kegiatan_id":1,
     "price":12000,
     "account_id":21,
     "acc_kode":"5.2.02.01.011",
     "acc_name":"Belanja Alat Tulis Kantor"

}
###
DELETE http://localhost:9000/api/expend_objects/15