POST http://localhost:9000/api/units
Content-Type: application/json

{
    "unit_kode":"1",
    "unit_name":"Komite Olahraga Nasional Indonesia",
    "unit_loc":"Jl. Pakansari, Kelurahan Pakansari, Cibinong, Bogor",
    "unit_abbr":"KONI KAB.BOGOR",
    "unit_head":"Dedi Ade Bachtiar, SE, MM, MBA",
    "unit_head_id":"000001",
    "unit_induk_head":"Dedi Ade Bachtiar, SE, MM, MBA",
    "unit_induk_head_id":"0000001",
    "root":true
}

###

PUT http://localhost:9000/api/units/1
Content-Type: application/json

{
    "unit_kode":"1",
    "unit_name":"Komite Olahraga Nasional Indonesia Kabupaten Bogor",
    "unit_loc":"Jl. Pakansari, Kelurahan Pakansari, Cibinong, Bogor",
    "unit_abbr":"KONI",
    "unit_head":"Dedi Ade Bachtiar, SE, MM, MBA",
    "unit_head_id":"000001",
    "unit_induk_head":"Dedi Ade Bachtiar, SE, MM, MBA",
    "unit_induk_head_id":"0000001",
    "root":true
}

###

GET http://localhost:9000/api/units/2

###

POST http://localhost:9000/api/units
Content-Type: application/json

{
    "unit_kode":"1.1",
    "unit_name":"Sekretariat",
    "unit_loc":"Jl. Pakansari, Kelurahan Pakansari, Cibinong, Bogor",
    "unit_abbr":"SEKRET",
    "unit_head":"Nungky",
    "unit_head_id":"000003",
    "unit_induk_id":1,
    "unit_induk_head":"Dedi Ade Bachtiar, SE, MM, MBA",
    "unit_induk_head_id":"0000001",
    "root":false
}

###

POST http://localhost:9000/api/units
Content-Type: application/json

{
    "unit_kode":"1.3",
    "unit_name":"Bidang Kerjasama",
    "unit_loc":"Jl. Pakansari, Kelurahan Pakansari, Cibinong, Bogor",
    "unit_abbr":"KERJASAMA",
    "unit_head":"Gandala Sonjaya",
    "unit_head_id":"000004",
    "unit_induk_id":1,
    "unit_induk_head":"Dedi Ade Bachtiar, SE, MM, MBA",
    "unit_induk_head_id":"0000001",
    "root":false
}

###

GET http://localhost:9000/api/units/sub

###


POST http://localhost:9000/api/programs
Content-Type: application/json

{
    "program_kode":"1.3.3",
    "program_name":"Program Pembiayaan Lintas Organisasi",
    "unit_name":"Bidang Kerjasama",
    "unit_kode":"1.3",
    "unit_id":5,
    "program_pagu":0.00
}

###

POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.2.1.1",
    "kegiatan_name":"Penyelenggaraan Pemusatan Pelatihan Daerah",
    "program_id":1,
    "program_kode":"1.2.1",
    "program_name":"Program Pelatihan Atlet Daerah"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.2.1.2",
    "kegiatan_name":"Penyelenggaraan Seleksi Atlet Daerah",
    "program_id":1,
    "program_kode":"1.2.1",
    "program_name":"Program Pelatihan Atlet Daerah"
}

###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.2.2.1",
    "kegiatan_name":"Inventarisasi Atlet Berprestasi Daerah",
    "program_id":2,
    "program_kode":"1.2.2",
    "program_name":"Program Penghargaan Atlet Daerah Berprestasi"
}

###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.2.2.2",
    "kegiatan_name":"Penyelenggaraan Penghargaan Atlet Berprestasi Daerah",
    "program_id":2,
    "program_kode":"1.2.2",
    "program_name":"Program Penghargaan Atlet Daerah Berprestasi"
}

###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.2.3.1",
    "kegiatan_name":"Penyelenggaraan Pencarian Bakat Atlet Luar Daerah",
    "program_id":3,
    "program_kode":"1.2.3",
    "program_name":"Program Pencarian Bakat Atlet Daerah"
}

###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.2.3.2",
    "kegiatan_name":"Penyelenggaraan Pencarian Bakat Atlet Dalam Daerah",
    "program_id":3,
    "program_kode":"1.2.3",
    "program_name":"Program Pencarian Bakat Atlet Daerah"
}

###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.1.1.1",
    "kegiatan_name":"Penyusunan Rancangan Rencana Kerja",
    "program_id":4,
    "program_kode":"1.1.1",
    "program_name":"Program Perencaan dan Pelaporan Organisasi"
}

###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.1.1.2",
    "kegiatan_name":"Penyusunan Anggaran Rencana Kerja",
    "program_id":4,
    "program_kode":"1.1.1",
    "program_name":"Program Perencaan dan Pelaporan Organisasi"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.1.1.3",
    "kegiatan_name":"Penyusunan Laporan Kegiatan Berkala",
    "program_id":4,
    "program_kode":"1.1.1",
    "program_name":"Program Perencaan dan Pelaporan Organisasi"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.1.2.1",
    "kegiatan_name":"Pengadaan Sarana dan Prasarana Pendukung Kantor",
    "program_id":5,
    "program_kode":"1.1.2",
    "program_name":"Program Penyediaan Perlengkapan Kantor"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.1.3.1",
    "kegiatan_name":"Pengadaan Sarana dan Prasarana Kantor",
    "program_id":6,
    "program_kode":"1.1.3",
    "program_name":"Program Penyediaan Peralatan Kantor"
}

###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.1.3.2",
    "kegiatan_name":"Pengadaan Kendaraan Operasional atau Lapangan",
    "program_id":6,
    "program_kode":"1.1.3",
    "program_name":"Program Penyediaan Peralatan Kantor"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.1.4.1",
    "kegiatan_name":"Pelaksanaan Penatusahaan dan Verifikasi Keuangan",
    "program_id":7,
    "program_kode":"1.1.4",
    "program_name":"Program Pengelolaan Keuangan"
}

###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.1.4.2",
    "kegiatan_name":"Penyusunan Laporan Keuangan Akhir Tahun",
    "program_id":7,
    "program_kode":"1.1.4",
    "program_name":"Program Pengelolaan Keuangan"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.1.5.1",
    "kegiatan_name":"Penyediaan Barang Cetakan dan Penggandaan",
    "program_id":8,
    "program_kode":"1.1.5",
    "program_name":"Program Administrasi Kantor"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.1.5.2",
    "kegiatan_name":"Fasilitasi Kunjungan Tamu",
    "program_id":8,
    "program_kode":"1.1.5",
    "program_name":"Program Administrasi Kantor"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.3.1.1",
    "kegiatan_name":"Pelatihan Bisnis Bagi Atlet Senior Daerah",
    "program_id":9,
    "program_kode":"1.3.1",
    "program_name":"Program Kewirausahaan Atlet Daerah"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.3.1.2",
    "kegiatan_name":"Pameran Prestasi Atlet Daerah",
    "program_id":9,
    "program_kode":"1.3.1",
    "program_name":"Program Kewirausahaan Atlet Daerah"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.3.2.1",
    "kegiatan_name":"Administrasi Pengeluaran Pembiayaan Kepada Organisasi Cabang Olahraga",
    "program_id":10,
    "program_kode":"1.3.2",
    "program_name":"Program Pembiayaan Lintas Organisasi"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.3.2.2",
    "kegiatan_name":"Administrasi Penerimaan Pembiayaan Dari Organisasi Vertikal",
    "program_id":10,
    "program_kode":"1.3.2",
    "program_name":"Program Pembiayaan Lintas Organisasi"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.3.3.1",
    "kegiatan_name":"Penerimaan Atlet Luar Daerah",
    "program_id":11,
    "program_kode":"1.3.3",
    "program_name":"Program Pertukaran Atlet Antar Daerah"
}
###
POST http://localhost:9000/api/kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.3.3.2",
    "kegiatan_name":"Pelepasan Atlet Dalam Daerah",
    "program_id":11,
    "program_kode":"1.3.3",
    "program_name":"Program Pertukaran Atlet Antar Daerah"
}


###
GET http://localhost:9000/api/programs/kegiatan/2
###

GET http://localhost:9000/api/programs/search?searchTerm=administrasi kantor
###
POST http://localhost:9000/api/programs/paginate
Content-Type: application/json

{
    "pageIndex":1,
    "pageSize":2,
    "query":"atlet",
    "sort":{
        "key":"program_id",
        "order":"asc"
    }
}

###
POST http://localhost:9000/api/kegiatans/paginate/1
Content-Type: application/json

{
    "pageIndex":1,
    "pageSize":2,
    "query":"seleksi",
    "sort":{
        "key":"program_id",
        "order":"asc"
    }
}

###

POST http://localhost:9000/api/programs
Content-Type: application/json

{
    "program_kode":"1.2.2",
    "program_name":"Program Penghargaan Atlet Daerah Berprestasi",
    "unit_name":"Bidang Pembinaan Prestasi",
    "unit_kode":"1.2",
    "unit_id":3,
    "program_pagu":0.00
}

###

POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"1",
    "acc_name":"Aset",
    "root":true,
    "report":"induk",
    "acc_type":"ASET",
    "acc_group":"NERACA"
}

###

POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"2",
    "acc_name":"Kewajiban",
    "root":true,
    "report":"induk",
    "acc_type":"KEWAJIBAN",
    "acc_group":"NERACA"
}

###

POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"3",
    "acc_name":"Ekuitas",
    "root":true,
    "report":"induk",
    "acc_type":"EKUITAS",
    "acc_group":"NERACA"
}

###

POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"4",
    "acc_name":"Pendapatan",
    "root":true,
    "report":"induk",
    "acc_type":"PENDAPATAN",
    "acc_group":"LRA"
}

###

POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"5",
    "acc_name":"Belanja",
    "root":true,
    "report":"induk",
    "acc_type":"BELANJA",
    "acc_group":"LRA"
}

###

POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"6",
    "acc_name":"Pembiayaan",
    "root":true,
    "report":"induk",
    "acc_type":"PEMBIAYAAN",
    "acc_group":"LRA"
}

###

POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"7",
    "acc_name":"Pendapatan-LO",
    "root":true,
    "report":"induk",
    "acc_type":"PENDAPATAN-LO",
    "acc_group":"LO"
}

###

POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"8",
    "acc_name":"Beban Operasi-LO",
    "root":true,
    "report":"induk",
    "acc_type":"BEBAN-LO",
    "acc_group":"LO"
}

###

POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"5.1",
    "acc_name":"Belanja Operasi",
    "root":false,
    "report":"k",
    "acc_type":"BELANJA",
    "acc_group":"LRA",
    "acc_parent_id":5
}

###

POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"5.2",
    "acc_name":"Belanja Modal",
    "root":false,
    "report":"kelompok",
    "acc_type":"BELANJA",
    "acc_group":"LRA",
    "acc_parent_id":5
}

###
POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"5.4",
    "acc_name":"Belanja Transfer",
    "root":false,
    "report":"kelompok",
    "acc_type":"BELANJA",
    "acc_group":"LRA",
    "acc_parent_id":5
}

###
POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"5.2.01",
    "acc_name":"Belanja Pegawai",
    "root":false,
    "report":"jenis",
    "acc_type":"BELANJA",
    "acc_group":"LRA",
    "acc_parent_id":12
}

###
POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"5.2.01.02",
    "acc_name":"Honorarium",
    "root":false,
    "report":"rincian objek",
    "acc_type":"BELANJA",
    "acc_group":"LRA",
    "acc_parent_id":10
}

###

POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"5.2.01.02.001",
    "acc_name":"Honorarium Pengurus",
    "root":false,
    "report":"rincian",
    "acc_type":"BELANJA",
    "acc_group":"LRA",
    "acc_parent_id":11
}

###
POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"5.2.02",
    "acc_name":"Belanja Barang Jasa",
    "root":false,
    "report":"jenis",
    "acc_type":"BELANJA",
    "acc_group":"LRA",
    "acc_parent_id":9
}
###
POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"5.2.02.01",
    "acc_name":"Belanja Pakai Habis",
    "root":false,
    "report":"rincian objek",
    "acc_type":"BELANJA",
    "acc_group":"LRA",
    "acc_parent_id":13
}

###
POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"5.2.02.01.011",
    "acc_name":"Belanja Alat Tulis Kantor",
    "root":false,
    "report":"rincian",
    "acc_type":"BELANJA",
    "acc_group":"LRA",
    "acc_parent_id":14
}

###
POST http://localhost:9000/api/accounts
Content-Type: application/json

{
    "acc_kode":"5.2.02.01.025",
    "acc_name":"Belanja Makan Minum Rapat",
    "root":false,
    "report":"rincian",
    "acc_type":"BELANJA",
    "acc_group":"LRA",
    "acc_parent_id":14
}

###

POST http://localhost:9000/api/budgets
Content-Type: application/json

{
    "budget_year":2024,
    "budget_status":0,
    "budget_data":"2024-01-01"
}

###
POST http://localhost:9000/api/expends
Content-Type: application/json

{
    "expend_year":2024,
    "expend_status":0,
    "unit_id":1,
    "unit_kode":"1",
    "unit_name":"Komite Olahraga Nasional Indonesia Kabupaten Bogor",
    "budget_id":1,
    "root":true
}

###
POST http://localhost:9000/api/expends
Content-Type: application/json

{
    "expend_year":2024,
    "expend_status":0,
    "unit_id":3,
    "unit_kode":"1.2",
    "unit_name":"Bidang Pembinaan Prestasi",
    "budget_id":1,
    "root":false,
    "expend_parent_id":1
}

###
POST http://localhost:9000/api/expend_programs
Content-Type: application/json

{
    "program_id":1,
    "program_kode":"1.2.1",
    "program_name":"Program Pembinaan Dan Pelatihan Atlet Daerah",
    "expend_parent_id":2
}

###
POST http://localhost:9000/api/expend_kegiatans
Content-Type: application/json

{
    "kegiatan_kode":"1.2.1.1",
    "kegiatan_name":"Penyelenggaraan Pemusatan Pelatihan Daerah",
    "kegiatan_id":1,
    "expend_program_id":1
}

###