version: '3.5'

services:
  postgres:
    container_name: postgres_kofin
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: kofin
      POSTGRES_USER: kofin
      POSTGRES_DB: kofin
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data