import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'

const navigationConfig = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'setting',
        path: '/home',
        title: 'Pengaturan',
        translateKey: 'nav.setting',
        icon: 'setting',
        type:NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'unit',
                path: '/setting/unit',
                title: 'Unit Kerja',
                translateKey: 'nav.unit',
                icon: 'unit',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'program',
                path: '/setting/programs',
                title: 'Program',
                icon: 'program',
                translateKey: 'nav.program',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            }
        ],
    },
    {
        key: 'budget',
        path: '',
        title: 'Anggaran',
        translateKey: 'nav.budget.anggaran',
        icon: 'budget',
        type:NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'setup',
                path: '/budget/setup',
                title: 'Setup',
                icon: 'setup',
                translateKey: 'nav.budget.setup',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'import',
                path: '',
                title: 'Import',
                translateKey: 'nav.budget.import',
                icon: 'inout',
                type:NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'import_program',
                        path: '/budget/import/program',
                        title: 'Program',
                        icon: 'program',
                        translateKey: 'nav.budget.program',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    // {
                    //     key: 'import_kegiatan',
                    //     path: '/budget/import/kegiatan',
                    //     title: 'Kegiatan',
                    //     icon: 'program',
                    //     translateKey: 'nav.budget.kegiatan',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [],
                    //     subMenu: [],
                    // }
                ]
            },
            {
                key: 'hapus',
                path: '',
                title: 'Hapus',
                translateKey: 'nav.budget.hapus',
                icon: 'hapus',
                type:NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'hapus_program',
                        path: '/budget/hapus/program',
                        title: 'Program',
                        icon: 'program',
                        translateKey: 'nav.budget.program',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    // {
                    //     key: 'hapus_kegiatan',
                    //     path: '/budget/hapus/kegiatan',
                    //     title: 'Kegiatan',
                    //     icon: 'program',
                    //     translateKey: 'nav.budget.kegiatan',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [],
                    //     subMenu: [],
                    // }
                ]
            },
            {
                key: 'rka',
                path: '/budget/setup',
                title: 'RKA',
                icon: 'rka',
                translateKey: 'nav.budget.rka',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ]
        
    },
    /** Example purpose only, please remove */
    {
        key: 'singleMenuItem',
        path: '/single-menu-view',
        title: 'Single menu item',
        translateKey: 'nav.singleMenuItem',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'collapseMenu',
        path: '',
        title: 'Collapse Menu',
        translateKey: 'nav.collapseMenu.collapseMenu',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.item1',
                path: '/collapse-menu-item-view-1',
                title: 'Collapse menu item 1',
                translateKey: 'nav.collapseMenu.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.item2',
                path: '/collapse-menu-item-view-2',
                title: 'Collapse menu item 2',
                translateKey: 'nav.collapseMenu.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'groupMenu',
        path: '',
        title: 'Group Menu',
        translateKey: 'nav.groupMenu.groupMenu',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'groupMenu.single',
                path: '/group-single-menu-item-view',
                title: 'Group single menu item',
                translateKey: 'nav.groupMenu.single',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'groupMenu.collapse',
                path: '',
                title: 'Group collapse menu',
                translateKey: 'nav.groupMenu.collapse.collapse',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'groupMenu.collapse.item1',
                        path: '/group-collapse-menu-item-view-1',
                        title: 'Menu item 1',
                        translateKey: 'nav.groupMenu.collapse.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'groupMenu.collapse.item2',
                        path: '/group-collapse-menu-item-view-2',
                        title: 'Menu item 2',
                        translateKey: 'nav.groupMenu.collapse.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
]

export default navigationConfig
